### ISSUE TITLE
error 500 after installing

### ISSUE THREAD

**Issue by deMathias** [waw-eve/seat-mumble-register#1]
If i got to settings in eve seat i get error 500. Even with debug on it shows not the error. I found in laravel log:

`[previous exception] [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of WarAndWormhole\\Seat\\MumbleRegister\\MumbleRegisterServiceProvider::getVersion() must be of the type string, null returned at /var/www/seat.ca-corp.tk/seat/vendor/alliancewaw/seat-mumble-register/src/MumbleRegisterServiceProvider.php:157)
[stacktrace]
#0 /var/www/seat.ca-corp.tk/seat/storage/framework/views/9934e92c5e7b7dde1fc66dcd411739332410ae9c.php(5): WarAndWormhole\\Seat\\MumbleRegister\\MumbleRegisterServiceProvider->getVersion()
#1 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/seat.c...')
#2 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/seat.c...', Array)
#3 /var/www/seat.ca-corp.tk/seat/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/seat.c...', Array)
#4 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/var/www/seat.c...', Array)
#5 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#6 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /var/www/seat.ca-corp.tk/seat/storage/framework/views/dab8ac9b434955b5114a2652099b4f220524999b.php(258): Illuminate\\View\\View->render()
#8 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/seat.c...')
#9 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/seat.c...', Array)
#10 /var/www/seat.ca-corp.tk/seat/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/seat.c...', Array)
#11 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/var/www/seat.c...', Array)
#12 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#13 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#14 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#15 /var/www/seat.ca-corp.tk/seat/vendor/symfony/http-foundation/Response.php(205): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#16 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#17 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#18 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#19 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'global.superuse...')
#22 /var/www/seat.ca-corp.tk/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/seat.ca-corp.tk/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/seat.ca-corp.tk/seat/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /var/www/seat.ca-corp.tk/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 /var/www/seat.ca-corp.tk/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 {main}
"} `

**Comment by KagurazakaNyaa** [comment]
Please describe the environment when this error occurs, including the php version, SeAT version, other plug-ins installed, and web server version. Please try to install SeAT using docker to verify whether this problem is resolved.

**Comment by KagurazakaNyaa** [comment]
It should be noted that this plugin needs to be used with https://github.com/waw-eve/seat-mumble-register-backend to complete the operation of mumble and the generation of certificates.

**Comment by deMathias** [comment]
Hello, I wasn't able to reproduce the error after a fresh seat install. I'm trying to configure the plugin for the first time now. Thanks for your work!

**Comment by MaximusLNK** [comment]
> It should be noted that this plugin needs to be used with https://github.com/waw-eve/seat-mumble-register-backend to complete the operation of mumble and the generation of certificates.

what about "bare metal"?

**Comment by KagurazakaNyaa** [comment]
> > It should be noted that this plugin needs to be used with https://github.com/waw-eve/seat-mumble-register-backend to complete the operation of mumble and the generation of certificates.
> 
> what about "bare metal"?

Add the following code to `app/build.gradle`
```
jar {
    manifest {
        attributes(
                'Main-Class': 'com.waw_eve.seat.mumble.App'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
 }
```
Then execute `gradle build`
You will find the files you need in `app/build/libs/app.jar`

**Comment by MaximusLNK** [comment]
> > > It should be noted that this plugin needs to be used with https://github.com/waw-eve/seat-mumble-register-backend to complete the operation of mumble and the generation of certificates.
> > 
> > 
> > what about "bare metal"?
> 
> Add the following code to `app/build.gradle`
> 
> ```
> jar {
>     manifest {
>         attributes(
>                 'Main-Class': 'com.waw_eve.seat.mumble.App'
>         )
>     }
>     from {
>         configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
>     }
>  }
> ```
> 
> Then execute `gradle build` You will find the files you need in `app/build/libs/app.jar`

It is possible a little more in detail? It is not clear how to make changes and install in SeaT

**Comment by KagurazakaNyaa** [comment]
> > > > It should be noted that this plugin needs to be used with https://github.com/waw-eve/seat-mumble-register-backend to complete the operation of mumble and the generation of certificates.
> > > 
> > > 
> > > what about "bare metal"?
> > 
> > 
> > Add the following code to `app/build.gradle`
> > ```
> > jar {
> >     manifest {
> >         attributes(
> >                 'Main-Class': 'com.waw_eve.seat.mumble.App'
> >         )
> >     }
> >     from {
> >         configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
> >     }
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then execute `gradle build` You will find the files you need in `app/build/libs/app.jar`
> 
> It is possible a little more in detail? It is not clear how to make changes and install in SeaT

This is a standalone Java application that provides webapi for mumble as a wrapper, so it needs to run independently and be able to connect to both the mumble server and the SeAT server.

**Comment by MaximusLNK** [comment]
Error 
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.google.cloud.tools.jib', version: '3.1.2']
> Failed to apply plugin [id 'com.google.cloud.tools.jib']
   > Detected Gradle 4.4.1, but jib requires Gradle 5.1 or higher. You can upgrade by running 'gradle wrapper --gradle-version=5.1'.
```

I try
`gradle wrapper --gradle-version=5.1`
