### ISSUE TITLE
It prompts you to download the "register" file when you try to register.

### ISSUE THREAD

**Issue by KsenZ** [waw-eve/seat-mumble-register#5]
When trying to register a user, SeAT prompts you to download a file with name "register".

**Comment by KagurazakaNyaa** [comment]
It should return a certificate file in p12/pfx format to the user, try modifying the file extension to '.p12' to import the certificate.

**Comment by KsenZ** [comment]
Hmm...
On Linux, it downloads the file "regiter" without an extension.
On Window, it downloads register.p12.
Thanks for your help!
